// Code generated by protoc-gen-go.
// source: type.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	type.proto

It has these top-level messages:
	CmdHeader
	MbTcpHeader
	MbWriteRequest
	MbTcpSingleWriteReq
	MbTcpMultipleWriteReq
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CmdHeader struct {
	Receiver string `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Sender   string `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	Version  uint32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Tid      uint64 `protobuf:"varint,4,opt,name=tid" json:"tid,omitempty"`
	Method   string `protobuf:"bytes,5,opt,name=method" json:"method,omitempty"`
}

func (m *CmdHeader) Reset()                    { *m = CmdHeader{} }
func (m *CmdHeader) String() string            { return proto.CompactTextString(m) }
func (*CmdHeader) ProtoMessage()               {}
func (*CmdHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MbTcpHeader struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Id   uint32 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
}

func (m *MbTcpHeader) Reset()                    { *m = MbTcpHeader{} }
func (m *MbTcpHeader) String() string            { return proto.CompactTextString(m) }
func (*MbTcpHeader) ProtoMessage()               {}
func (*MbTcpHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MbWriteRequest struct {
	Code     uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Register uint32 `protobuf:"varint,2,opt,name=register" json:"register,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Alias    string `protobuf:"bytes,5,opt,name=alias" json:"alias,omitempty"`
}

func (m *MbWriteRequest) Reset()                    { *m = MbWriteRequest{} }
func (m *MbWriteRequest) String() string            { return proto.CompactTextString(m) }
func (*MbWriteRequest) ProtoMessage()               {}
func (*MbWriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MbTcpSingleWriteReq struct {
	CmdHeader      *CmdHeader      `protobuf:"bytes,1,opt,name=cmd_header,json=cmdHeader" json:"cmd_header,omitempty"`
	MbTcpHeader    *MbTcpHeader    `protobuf:"bytes,2,opt,name=mb_tcp_header,json=mbTcpHeader" json:"mb_tcp_header,omitempty"`
	MbWriteRequest *MbWriteRequest `protobuf:"bytes,3,opt,name=mb_write_request,json=mbWriteRequest" json:"mb_write_request,omitempty"`
}

func (m *MbTcpSingleWriteReq) Reset()                    { *m = MbTcpSingleWriteReq{} }
func (m *MbTcpSingleWriteReq) String() string            { return proto.CompactTextString(m) }
func (*MbTcpSingleWriteReq) ProtoMessage()               {}
func (*MbTcpSingleWriteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MbTcpSingleWriteReq) GetCmdHeader() *CmdHeader {
	if m != nil {
		return m.CmdHeader
	}
	return nil
}

func (m *MbTcpSingleWriteReq) GetMbTcpHeader() *MbTcpHeader {
	if m != nil {
		return m.MbTcpHeader
	}
	return nil
}

func (m *MbTcpSingleWriteReq) GetMbWriteRequest() *MbWriteRequest {
	if m != nil {
		return m.MbWriteRequest
	}
	return nil
}

type MbTcpMultipleWriteReq struct {
	CmdHeader   *CmdHeader        `protobuf:"bytes,1,opt,name=cmd_header,json=cmdHeader" json:"cmd_header,omitempty"`
	MbTcpHeader *MbTcpHeader      `protobuf:"bytes,2,opt,name=mb_tcp_header,json=mbTcpHeader" json:"mb_tcp_header,omitempty"`
	Requests    []*MbWriteRequest `protobuf:"bytes,3,rep,name=requests" json:"requests,omitempty"`
}

func (m *MbTcpMultipleWriteReq) Reset()                    { *m = MbTcpMultipleWriteReq{} }
func (m *MbTcpMultipleWriteReq) String() string            { return proto.CompactTextString(m) }
func (*MbTcpMultipleWriteReq) ProtoMessage()               {}
func (*MbTcpMultipleWriteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MbTcpMultipleWriteReq) GetCmdHeader() *CmdHeader {
	if m != nil {
		return m.CmdHeader
	}
	return nil
}

func (m *MbTcpMultipleWriteReq) GetMbTcpHeader() *MbTcpHeader {
	if m != nil {
		return m.MbTcpHeader
	}
	return nil
}

func (m *MbTcpMultipleWriteReq) GetRequests() []*MbWriteRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*CmdHeader)(nil), "main.CmdHeader")
	proto.RegisterType((*MbTcpHeader)(nil), "main.MbTcpHeader")
	proto.RegisterType((*MbWriteRequest)(nil), "main.MbWriteRequest")
	proto.RegisterType((*MbTcpSingleWriteReq)(nil), "main.MbTcpSingleWriteReq")
	proto.RegisterType((*MbTcpMultipleWriteReq)(nil), "main.MbTcpMultipleWriteReq")
}

var fileDescriptor0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x52, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x55, 0xda, 0xb4, 0xdf, 0x97, 0x1b, 0xa5, 0x14, 0x53, 0x50, 0xc4, 0x84, 0x32, 0x31, 0x45,
	0xa8, 0x88, 0x15, 0x09, 0xb1, 0xb0, 0x74, 0x31, 0x48, 0x8c, 0x55, 0x7e, 0xae, 0x5a, 0x4b, 0xf9,
	0xc3, 0x71, 0x8b, 0xd8, 0x90, 0x78, 0x21, 0x1e, 0x80, 0x87, 0xc3, 0xbe, 0x4e, 0xa2, 0x32, 0xb0,
	0xb2, 0xdd, 0x13, 0xdf, 0x73, 0x7c, 0xce, 0x71, 0x00, 0xd4, 0x5b, 0x83, 0x71, 0x23, 0x6b, 0x55,
	0x33, 0xb7, 0x4c, 0x44, 0x15, 0x7d, 0x38, 0xe0, 0xdd, 0x97, 0xf9, 0x03, 0x26, 0x39, 0x4a, 0x76,
	0x0e, 0xff, 0x25, 0x66, 0x28, 0xf6, 0x28, 0x43, 0xe7, 0xc2, 0xb9, 0xf4, 0xf8, 0x80, 0xd9, 0x19,
	0x4c, 0x5b, 0xac, 0xf4, 0x56, 0x38, 0xa2, 0x93, 0x0e, 0xb1, 0x10, 0xfe, 0xe9, 0xe3, 0x56, 0xd4,
	0x55, 0x38, 0xd6, 0x07, 0x01, 0xef, 0x21, 0x9b, 0xc3, 0x58, 0x89, 0x3c, 0x74, 0xf5, 0x57, 0x97,
	0x9b, 0xd1, 0x68, 0x94, 0xa8, 0xb6, 0x75, 0x1e, 0x4e, 0xac, 0x86, 0x45, 0xd1, 0x1d, 0xf8, 0xab,
	0xf4, 0x29, 0x6b, 0x3a, 0x1b, 0x33, 0x18, 0x89, 0xa6, 0x33, 0xa0, 0x27, 0xc6, 0xc0, 0x6d, 0x6a,
	0xa9, 0xe8, 0xe2, 0x80, 0xd3, 0x4c, 0x3b, 0x79, 0x77, 0xa3, 0x9e, 0xa2, 0x77, 0x07, 0x66, 0xab,
	0xf4, 0x59, 0x0a, 0x85, 0x1c, 0x5f, 0x76, 0xd8, 0x2a, 0x43, 0xcb, 0xea, 0x1c, 0x49, 0x48, 0xd3,
	0xcc, 0x6c, 0x13, 0x6e, 0x44, 0xab, 0xba, 0x1c, 0x01, 0x1f, 0x30, 0x5b, 0xc0, 0x64, 0x9f, 0x14,
	0x3b, 0x24, 0x55, 0x8f, 0x5b, 0x60, 0x54, 0x4c, 0x6b, 0x14, 0xc3, 0xe3, 0x34, 0x9b, 0xcd, 0xa4,
	0x10, 0x49, 0xdb, 0xc5, 0xb0, 0x20, 0xfa, 0x72, 0xe0, 0x84, 0x62, 0x3c, 0x8a, 0x6a, 0x53, 0x60,
	0xef, 0x85, 0xc5, 0x00, 0x59, 0x99, 0xaf, 0xb7, 0x14, 0x8e, 0xdc, 0xf8, 0xcb, 0xa3, 0xd8, 0xd4,
	0x1f, 0x0f, 0xd5, 0x73, 0x2f, 0x1b, 0x5e, 0xe1, 0x06, 0x82, 0x32, 0x5d, 0xab, 0xac, 0xe9, 0x29,
	0x23, 0xa2, 0x1c, 0x5b, 0xca, 0x41, 0x51, 0xdc, 0x2f, 0x0f, 0x5a, 0xbb, 0x85, 0xb9, 0xa6, 0xbd,
	0x9a, 0x5b, 0xd7, 0xd2, 0x56, 0x40, 0x49, 0xfc, 0xe5, 0xa2, 0x67, 0x1e, 0xd6, 0xc3, 0x67, 0xe5,
	0x0f, 0x1c, 0x7d, 0x3a, 0x70, 0x4a, 0xe2, 0xab, 0x5d, 0xa1, 0x44, 0xf3, 0xf7, 0x01, 0xae, 0xcc,
	0xdb, 0x90, 0x97, 0x56, 0x1b, 0x1f, 0xff, 0x6a, 0x7c, 0xd8, 0x4a, 0xa7, 0xf4, 0x2b, 0x5f, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x8a, 0x69, 0x0d, 0xd8, 0x02, 0x00, 0x00,
}
