/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: type2.proto */

#ifndef PROTOBUF_C_type2_2eproto__INCLUDED
#define PROTOBUF_C_type2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CmdHeader CmdHeader;
typedef struct _MbTcpHeader MbTcpHeader;
typedef struct _MbWriteRequest MbWriteRequest;
typedef struct _MbTcpSingleWriteReq MbTcpSingleWriteReq;


/* --- enums --- */


/* --- messages --- */

struct  _CmdHeader
{
  ProtobufCMessage base;
  /*
   * receiver
   */
  char *receiver;
  /*
   * sender
   */
  char *sender;
  /*
   * protocol version
   */
  uint32_t version;
  uint64_t tid;
  /*
   * command name
   */
  char *method;
};
#define CMD_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmd_header__descriptor) \
    , NULL, NULL, NULL, 0, NULL }


struct  _MbTcpHeader
{
  ProtobufCMessage base;
  char *ip;
  uint32_t port;
  uint32_t id;
};
#define MB_TCP_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mb_tcp_header__descriptor) \
    , NULL, 0, 0 }


struct  _MbWriteRequest
{
  ProtobufCMessage base;
  /*
   * modbus function code
   */
  uint32_t code;
  /*
   * register start address
   */
  uint32_t register_;
  /*
   * data value
   */
  char *value;
  /*
   * data type
   */
  char *type;
  /*
   * human friendly name
   */
  char *alias;
};
#define MB_WRITE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mb_write_request__descriptor) \
    , 0, 0, NULL, NULL, NULL }


struct  _MbTcpSingleWriteReq
{
  ProtobufCMessage base;
  CmdHeader *cmd_header;
  MbTcpHeader *mb_tcp_header;
  MbWriteRequest *mb_write_request;
};
#define MB_TCP_SINGLE_WRITE_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mb_tcp_single_write_req__descriptor) \
    , NULL, NULL, NULL }


/* CmdHeader methods */
void   cmd_header__init
                     (CmdHeader         *message);
size_t cmd_header__get_packed_size
                     (const CmdHeader   *message);
size_t cmd_header__pack
                     (const CmdHeader   *message,
                      uint8_t             *out);
size_t cmd_header__pack_to_buffer
                     (const CmdHeader   *message,
                      ProtobufCBuffer     *buffer);
CmdHeader *
       cmd_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmd_header__free_unpacked
                     (CmdHeader *message,
                      ProtobufCAllocator *allocator);
/* MbTcpHeader methods */
void   mb_tcp_header__init
                     (MbTcpHeader         *message);
size_t mb_tcp_header__get_packed_size
                     (const MbTcpHeader   *message);
size_t mb_tcp_header__pack
                     (const MbTcpHeader   *message,
                      uint8_t             *out);
size_t mb_tcp_header__pack_to_buffer
                     (const MbTcpHeader   *message,
                      ProtobufCBuffer     *buffer);
MbTcpHeader *
       mb_tcp_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mb_tcp_header__free_unpacked
                     (MbTcpHeader *message,
                      ProtobufCAllocator *allocator);
/* MbWriteRequest methods */
void   mb_write_request__init
                     (MbWriteRequest         *message);
size_t mb_write_request__get_packed_size
                     (const MbWriteRequest   *message);
size_t mb_write_request__pack
                     (const MbWriteRequest   *message,
                      uint8_t             *out);
size_t mb_write_request__pack_to_buffer
                     (const MbWriteRequest   *message,
                      ProtobufCBuffer     *buffer);
MbWriteRequest *
       mb_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mb_write_request__free_unpacked
                     (MbWriteRequest *message,
                      ProtobufCAllocator *allocator);
/* MbTcpSingleWriteReq methods */
void   mb_tcp_single_write_req__init
                     (MbTcpSingleWriteReq         *message);
size_t mb_tcp_single_write_req__get_packed_size
                     (const MbTcpSingleWriteReq   *message);
size_t mb_tcp_single_write_req__pack
                     (const MbTcpSingleWriteReq   *message,
                      uint8_t             *out);
size_t mb_tcp_single_write_req__pack_to_buffer
                     (const MbTcpSingleWriteReq   *message,
                      ProtobufCBuffer     *buffer);
MbTcpSingleWriteReq *
       mb_tcp_single_write_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mb_tcp_single_write_req__free_unpacked
                     (MbTcpSingleWriteReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CmdHeader_Closure)
                 (const CmdHeader *message,
                  void *closure_data);
typedef void (*MbTcpHeader_Closure)
                 (const MbTcpHeader *message,
                  void *closure_data);
typedef void (*MbWriteRequest_Closure)
                 (const MbWriteRequest *message,
                  void *closure_data);
typedef void (*MbTcpSingleWriteReq_Closure)
                 (const MbTcpSingleWriteReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cmd_header__descriptor;
extern const ProtobufCMessageDescriptor mb_tcp_header__descriptor;
extern const ProtobufCMessageDescriptor mb_write_request__descriptor;
extern const ProtobufCMessageDescriptor mb_tcp_single_write_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_type2_2eproto__INCLUDED */