/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: type2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "type2.pb-c.h"
void   main__cmd_header__init
                     (Main__CmdHeader         *message)
{
  static Main__CmdHeader init_value = MAIN__CMD_HEADER__INIT;
  *message = init_value;
}
size_t main__cmd_header__get_packed_size
                     (const Main__CmdHeader *message)
{
  assert(message->base.descriptor == &main__cmd_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__cmd_header__pack
                     (const Main__CmdHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__cmd_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__cmd_header__pack_to_buffer
                     (const Main__CmdHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__cmd_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__CmdHeader *
       main__cmd_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__CmdHeader *)
     protobuf_c_message_unpack (&main__cmd_header__descriptor,
                                allocator, len, data);
}
void   main__cmd_header__free_unpacked
                     (Main__CmdHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &main__cmd_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__mb_tcp_header__init
                     (Main__MbTcpHeader         *message)
{
  static Main__MbTcpHeader init_value = MAIN__MB_TCP_HEADER__INIT;
  *message = init_value;
}
size_t main__mb_tcp_header__get_packed_size
                     (const Main__MbTcpHeader *message)
{
  assert(message->base.descriptor == &main__mb_tcp_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__mb_tcp_header__pack
                     (const Main__MbTcpHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__mb_tcp_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__mb_tcp_header__pack_to_buffer
                     (const Main__MbTcpHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__mb_tcp_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__MbTcpHeader *
       main__mb_tcp_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__MbTcpHeader *)
     protobuf_c_message_unpack (&main__mb_tcp_header__descriptor,
                                allocator, len, data);
}
void   main__mb_tcp_header__free_unpacked
                     (Main__MbTcpHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &main__mb_tcp_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__mb_write_request__init
                     (Main__MbWriteRequest         *message)
{
  static Main__MbWriteRequest init_value = MAIN__MB_WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t main__mb_write_request__get_packed_size
                     (const Main__MbWriteRequest *message)
{
  assert(message->base.descriptor == &main__mb_write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__mb_write_request__pack
                     (const Main__MbWriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__mb_write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__mb_write_request__pack_to_buffer
                     (const Main__MbWriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__mb_write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__MbWriteRequest *
       main__mb_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__MbWriteRequest *)
     protobuf_c_message_unpack (&main__mb_write_request__descriptor,
                                allocator, len, data);
}
void   main__mb_write_request__free_unpacked
                     (Main__MbWriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &main__mb_write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__mb_tcp_single_write_req__init
                     (Main__MbTcpSingleWriteReq         *message)
{
  static Main__MbTcpSingleWriteReq init_value = MAIN__MB_TCP_SINGLE_WRITE_REQ__INIT;
  *message = init_value;
}
size_t main__mb_tcp_single_write_req__get_packed_size
                     (const Main__MbTcpSingleWriteReq *message)
{
  assert(message->base.descriptor == &main__mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__mb_tcp_single_write_req__pack
                     (const Main__MbTcpSingleWriteReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__mb_tcp_single_write_req__pack_to_buffer
                     (const Main__MbTcpSingleWriteReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__MbTcpSingleWriteReq *
       main__mb_tcp_single_write_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__MbTcpSingleWriteReq *)
     protobuf_c_message_unpack (&main__mb_tcp_single_write_req__descriptor,
                                allocator, len, data);
}
void   main__mb_tcp_single_write_req__free_unpacked
                     (Main__MbTcpSingleWriteReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &main__mb_tcp_single_write_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor main__cmd_header__field_descriptors[5] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__CmdHeader, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__CmdHeader, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__CmdHeader, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Main__CmdHeader, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__CmdHeader, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__cmd_header__field_indices_by_name[] = {
  4,   /* field[4] = method */
  0,   /* field[0] = receiver */
  1,   /* field[1] = sender */
  3,   /* field[3] = tid */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange main__cmd_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor main__cmd_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.CmdHeader",
  "CmdHeader",
  "Main__CmdHeader",
  "main",
  sizeof(Main__CmdHeader),
  5,
  main__cmd_header__field_descriptors,
  main__cmd_header__field_indices_by_name,
  1,  main__cmd_header__number_ranges,
  (ProtobufCMessageInit) main__cmd_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__mb_tcp_header__field_descriptors[3] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpHeader, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpHeader, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__mb_tcp_header__field_indices_by_name[] = {
  2,   /* field[2] = id */
  0,   /* field[0] = ip */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange main__mb_tcp_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__mb_tcp_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.MbTcpHeader",
  "MbTcpHeader",
  "Main__MbTcpHeader",
  "main",
  sizeof(Main__MbTcpHeader),
  3,
  main__mb_tcp_header__field_descriptors,
  main__mb_tcp_header__field_indices_by_name,
  1,  main__mb_tcp_header__number_ranges,
  (ProtobufCMessageInit) main__mb_tcp_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__mb_write_request__field_descriptors[5] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__MbWriteRequest, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__MbWriteRequest, register_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__MbWriteRequest, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__MbWriteRequest, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alias",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__MbWriteRequest, alias),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__mb_write_request__field_indices_by_name[] = {
  4,   /* field[4] = alias */
  0,   /* field[0] = code */
  1,   /* field[1] = register */
  3,   /* field[3] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange main__mb_write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor main__mb_write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.MbWriteRequest",
  "MbWriteRequest",
  "Main__MbWriteRequest",
  "main",
  sizeof(Main__MbWriteRequest),
  5,
  main__mb_write_request__field_descriptors,
  main__mb_write_request__field_indices_by_name,
  1,  main__mb_write_request__number_ranges,
  (ProtobufCMessageInit) main__mb_write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__mb_tcp_single_write_req__field_descriptors[3] =
{
  {
    "cmd_header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpSingleWriteReq, cmd_header),
    &main__cmd_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mb_tcp_header",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpSingleWriteReq, mb_tcp_header),
    &main__mb_tcp_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mb_write_request",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Main__MbTcpSingleWriteReq, mb_write_request),
    &main__mb_write_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__mb_tcp_single_write_req__field_indices_by_name[] = {
  0,   /* field[0] = cmd_header */
  1,   /* field[1] = mb_tcp_header */
  2,   /* field[2] = mb_write_request */
};
static const ProtobufCIntRange main__mb_tcp_single_write_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main__mb_tcp_single_write_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.MbTcpSingleWriteReq",
  "MbTcpSingleWriteReq",
  "Main__MbTcpSingleWriteReq",
  "main",
  sizeof(Main__MbTcpSingleWriteReq),
  3,
  main__mb_tcp_single_write_req__field_descriptors,
  main__mb_tcp_single_write_req__field_indices_by_name,
  1,  main__mb_tcp_single_write_req__number_ranges,
  (ProtobufCMessageInit) main__mb_tcp_single_write_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};