/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: type2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "type2.pb-c.h"
void   cmd_header__init
                     (CmdHeader         *message)
{
  static CmdHeader init_value = CMD_HEADER__INIT;
  *message = init_value;
}
size_t cmd_header__get_packed_size
                     (const CmdHeader *message)
{
  assert(message->base.descriptor == &cmd_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_header__pack
                     (const CmdHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_header__pack_to_buffer
                     (const CmdHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdHeader *
       cmd_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdHeader *)
     protobuf_c_message_unpack (&cmd_header__descriptor,
                                allocator, len, data);
}
void   cmd_header__free_unpacked
                     (CmdHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmd_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mb_tcp_header__init
                     (MbTcpHeader         *message)
{
  static MbTcpHeader init_value = MB_TCP_HEADER__INIT;
  *message = init_value;
}
size_t mb_tcp_header__get_packed_size
                     (const MbTcpHeader *message)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mb_tcp_header__pack
                     (const MbTcpHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mb_tcp_header__pack_to_buffer
                     (const MbTcpHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MbTcpHeader *
       mb_tcp_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MbTcpHeader *)
     protobuf_c_message_unpack (&mb_tcp_header__descriptor,
                                allocator, len, data);
}
void   mb_tcp_header__free_unpacked
                     (MbTcpHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mb_write_request__init
                     (MbWriteRequest         *message)
{
  static MbWriteRequest init_value = MB_WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t mb_write_request__get_packed_size
                     (const MbWriteRequest *message)
{
  assert(message->base.descriptor == &mb_write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mb_write_request__pack
                     (const MbWriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mb_write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mb_write_request__pack_to_buffer
                     (const MbWriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mb_write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MbWriteRequest *
       mb_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MbWriteRequest *)
     protobuf_c_message_unpack (&mb_write_request__descriptor,
                                allocator, len, data);
}
void   mb_write_request__free_unpacked
                     (MbWriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mb_write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mb_tcp_single_write_req__init
                     (MbTcpSingleWriteReq         *message)
{
  static MbTcpSingleWriteReq init_value = MB_TCP_SINGLE_WRITE_REQ__INIT;
  *message = init_value;
}
size_t mb_tcp_single_write_req__get_packed_size
                     (const MbTcpSingleWriteReq *message)
{
  assert(message->base.descriptor == &mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mb_tcp_single_write_req__pack
                     (const MbTcpSingleWriteReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mb_tcp_single_write_req__pack_to_buffer
                     (const MbTcpSingleWriteReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mb_tcp_single_write_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MbTcpSingleWriteReq *
       mb_tcp_single_write_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MbTcpSingleWriteReq *)
     protobuf_c_message_unpack (&mb_tcp_single_write_req__descriptor,
                                allocator, len, data);
}
void   mb_tcp_single_write_req__free_unpacked
                     (MbTcpSingleWriteReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mb_tcp_single_write_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cmd_header__field_descriptors[5] =
{
  {
    "receiver",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdHeader, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdHeader, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CmdHeader, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CmdHeader, tid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdHeader, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_header__field_indices_by_name[] = {
  4,   /* field[4] = method */
  0,   /* field[0] = receiver */
  1,   /* field[1] = sender */
  3,   /* field[3] = tid */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange cmd_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cmd_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdHeader",
  "CmdHeader",
  "CmdHeader",
  "",
  sizeof(CmdHeader),
  5,
  cmd_header__field_descriptors,
  cmd_header__field_indices_by_name,
  1,  cmd_header__number_ranges,
  (ProtobufCMessageInit) cmd_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mb_tcp_header__field_descriptors[3] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mb_tcp_header__field_indices_by_name[] = {
  2,   /* field[2] = id */
  0,   /* field[0] = ip */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange mb_tcp_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mb_tcp_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MbTcpHeader",
  "MbTcpHeader",
  "MbTcpHeader",
  "",
  sizeof(MbTcpHeader),
  3,
  mb_tcp_header__field_descriptors,
  mb_tcp_header__field_indices_by_name,
  1,  mb_tcp_header__number_ranges,
  (ProtobufCMessageInit) mb_tcp_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mb_write_request__field_descriptors[5] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbWriteRequest, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbWriteRequest, register_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MbWriteRequest, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MbWriteRequest, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alias",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MbWriteRequest, alias),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mb_write_request__field_indices_by_name[] = {
  4,   /* field[4] = alias */
  0,   /* field[0] = code */
  1,   /* field[1] = register */
  3,   /* field[3] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange mb_write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mb_write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MbWriteRequest",
  "MbWriteRequest",
  "MbWriteRequest",
  "",
  sizeof(MbWriteRequest),
  5,
  mb_write_request__field_descriptors,
  mb_write_request__field_indices_by_name,
  1,  mb_write_request__number_ranges,
  (ProtobufCMessageInit) mb_write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mb_tcp_single_write_req__field_descriptors[3] =
{
  {
    "cmd_header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MbTcpSingleWriteReq, cmd_header),
    &cmd_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mb_tcp_header",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MbTcpSingleWriteReq, mb_tcp_header),
    &mb_tcp_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mb_write_request",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MbTcpSingleWriteReq, mb_write_request),
    &mb_write_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mb_tcp_single_write_req__field_indices_by_name[] = {
  0,   /* field[0] = cmd_header */
  1,   /* field[1] = mb_tcp_header */
  2,   /* field[2] = mb_write_request */
};
static const ProtobufCIntRange mb_tcp_single_write_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mb_tcp_single_write_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MbTcpSingleWriteReq",
  "MbTcpSingleWriteReq",
  "MbTcpSingleWriteReq",
  "",
  sizeof(MbTcpSingleWriteReq),
  3,
  mb_tcp_single_write_req__field_descriptors,
  mb_tcp_single_write_req__field_indices_by_name,
  1,  mb_tcp_single_write_req__number_ranges,
  (ProtobufCMessageInit) mb_tcp_single_write_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};