/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: type2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "type2.pb-c.h"
void   mb_tcp_header__init
                     (MbTcpHeader         *message)
{
  static MbTcpHeader init_value = MB_TCP_HEADER__INIT;
  *message = init_value;
}
size_t mb_tcp_header__get_packed_size
                     (const MbTcpHeader *message)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mb_tcp_header__pack
                     (const MbTcpHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mb_tcp_header__pack_to_buffer
                     (const MbTcpHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MbTcpHeader *
       mb_tcp_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MbTcpHeader *)
     protobuf_c_message_unpack (&mb_tcp_header__descriptor,
                                allocator, len, data);
}
void   mb_tcp_header__free_unpacked
                     (MbTcpHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mb_tcp_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mb_tcp_header__field_descriptors[3] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MbTcpHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mb_tcp_header__field_indices_by_name[] = {
  2,   /* field[2] = id */
  0,   /* field[0] = ip */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange mb_tcp_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mb_tcp_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MbTcpHeader",
  "MbTcpHeader",
  "MbTcpHeader",
  "",
  sizeof(MbTcpHeader),
  3,
  mb_tcp_header__field_descriptors,
  mb_tcp_header__field_indices_by_name,
  1,  mb_tcp_header__number_ranges,
  (ProtobufCMessageInit) mb_tcp_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};